--BÀI TẬP CHƯƠNG 3
-- 1.
SELECT EMPNO, DEPTNO, SAL
FROM EMP
WHERE SAL BETWEEN 1000 AND 2000;

--2.
SELECT DEPTNO, DNAME
FROM DEPT
ORDER BY DNAME ASC;

--3.
SELECT *
FROM EMP
WHERE DEPTNO = 10 OR DEPTNO = 20
ORDER BY ENAME ASC;

--4.
SELECT ENAME, JOB
FROM EMP
WHERE JOB = 'CLERK' AND DEPTNO = 20;

--5.
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%TH%' OR ENAME LIKE '%TL%';

--6.
SELECT ENAME, JOB, SAL
FROM EMP
WHERE JOB NOT LIKE 'PRESIDENT';

--7.
SELECT ENAME, DEPTNO, HIREDATE
FROM EMP
WHERE TO_CHAR(HIREDATE, 'YYYY') = 1983

--8.
SELECT ENAME, (SAL * 12) AS ANUAL_SAL, COMM
FROM EMP
WHERE SAL > COMM AND JOB = 'SALESMAN'
ORDER BY SAL DESC, ENAME ASC