--BÀI TẬP CHƯƠNG 2
-- 1.
SELECT DISTINCT *
FROM SALGRADE;

-- 2.
SELECT DISTINCT *
FROM EMP;

-- 3.
SELECT DISTINCT *
FROM EMP
WHERE JOB = 'ANALYST'
   OR JOB = 'CLERK'
   OR JOB = 'MANAGER'
   OR JOB = 'PRESIDENT'
   OR JOB = 'SALESMAN';

-- 4.
SELECT DISTINCT ENAME, (SAL * 12) AS REMUNERATION
FROM EMP;

-- 5.
SELECT ENAME || 'HAS HELP THE POSITION OF ' || JOB || 'IN DEPT ' || DEPT_NO || 'SINCE ' || TO_CHAR(HIREDATE, 'DD-MM-YYYY')
FROM EMP;

-- 6.
DESC EMP;

-- 7.
SELECT DISTINCT TO_CHAR(SAL, '9,999.00') AS SALARY,
                TO_CHAR(HIREDATE, 'DD-MM-YYYY') AS DATE_NGAY
FROM EMP;
