--BÀI TẬP CHƯƠNG 7
--1.Tạo bảng PROJECT với các column được chỉ ra dưới đây, PROJID là promary key, và
--P_END_DATE > P_START_DATE.
CREATE TABLE PROJECT_HOADT
(
    PROJID NUMBER(4) NOT NULL CONSTRAINT PK_PROJIECT_HOADT PRIMARY KEY ,
    P_DESC VARCHAR2(20) NOT NULL,
    P_START_DATE DATE,
    P_END_DATE DATE,
    BUDGET_AMOUNT NUMBER(7,2) NOT NULL,
    MAX_NO_SATFF NUMBER(2),
    CHECK ( P_END_DATE > P_START_DATE )
);

SELECT * FROM PROJECT_HOADT

--2. Tạo bảng ASSIGNMENTS với các column được chỉ ra dưới đây, đồng thời cột
--PROJID là foreign key tới bảng PROJECT, cột EMPNO là foreign key tới bảng EMP.
CREATE TABLE ASSIGNMENTS_HOADT
(
    PROJID NUMBER(4) NOT NULL CONSTRAINT FK_PROJID_HOADT REFERENCES SCOTT.PROJECT_HOADT(PROJID),
    EMPNO NUMBER(4) NOT NULL CONSTRAINT FK_EMPNO_HOADT REFERENCES SCOTT.EMP(EMPNO),
    A_START_DATE DATE,
    A_END_DATE DATE,
    BILL_AMOUNT NUMBER(4,2),
    ASSIGN_TYPE VARCHAR2(2)
);

--3. Thêm column COMMENTS kiểu LONG vào bảng PROJECTS. Thêm column HOURS kiểu
--NUMBER vào bảng ASSIGNMENTS.
ALTER TABLE PROJECT_HOADT
ADD (COMMENTS LONG);

ALTER TABLE ASSIGNMENTS_HOADT
ADD ( HOURS NUMBER );

--4. Sử dụng view USER_OBJECTS hiển thị tất cả các đối tượng user sở hữu.
SELECT *
FROM SCOTT.USER_OBJECTS

--5. Thêm ràng buộc duy nhất (UNIQUE) cho 2 column PROJECT_ID và EMPNO của bảng
--ASSIGNMENTS.
ALTER TABLE ASSIGNMENTS_HOADT
MODIFY (CONSTRAINT UNQ_ASSIGNMENTS_HOADT UNIQUE(PROJID,EMPNO));

--6. Xem các thông tin về các ràng buộc trong USER_CONSTRAINTS.
SELECT *
FROM USER_CONSTRAINTS

--7. Xem trong USER hiện tại có tất cả bao nhiêu bảng.
SELECT COUNT(TABLE_NAME) SL_BANG
FROM DICTIONARY
