CREATE TABLE DOTATHOA_NHAXUATBAN
(
    ID NUMBER(4) NOT NULL CONSTRAINT PK_NHAXUATBAN_HOADT PRIMARY KEY,
    MA_NXB NUMBER(4) NOT NULL CONSTRAINT UN_NHAXUATBAN_HOADT UNIQUE,
    TEN_NXB VARCHAR2(50),
    TRANG_THAI NUMBER(1),
    DIA_CHI VARCHAR2(50),
    MO_TA VARCHAR2(100)
);

CREATE TABLE DOTATHOA_TACGIA
(
    ID NUMBER(4) NOT NULL CONSTRAINT PK_TACGIA_HOADT PRIMARY KEY,
    MA_TACGIA NUMBER(4) NOT NULL CONSTRAINT UN_TACGIA_HOADT UNIQUE ,
    TEN_TACGIA VARCHAR2(50),
    SODIENTHOAI VARCHAR2(12),
    DIA_CHI VARCHAR2(50),
    MO_TA VARCHAR2(100)
);

CREATE TABLE DOTATHOA_SACH
(
    ID NUMBER(4) NOT NULL CONSTRAINT PK_SACH_HOADT PRIMARY KEY ,
    MA_SACH NUMBER(4) NOT NULL CONSTRAINT UN_SACH_HOADT UNIQUE ,
    TEN_SACH VARCHAR2(50),
    ID_NXB NUMBER(4) CONSTRAINT FK_SACH_NXB_HOADT REFERENCES SCOTT.DOTATHOA_NHAXUATBAN(ID),
    ID_TACGIA NUMBER(4) CONSTRAINT FK_SACH_TACGIA_HOADT REFERENCES SCOTT.DOTATHOA_TACGIA(ID),
    CHU_DE VARCHAR2(50),
    NAM_XUAT_BAN DATE,
    MO_TA VARCHAR2(100),
    SO_LUONG_CON_LAI NUMBER(4),
    SO_LUONG_DANG_MUON NUMBER(4),
    TONG_SO_SACH NUMBER(5)
);

CREATE TABLE DOTATHOA_BANDOC
(
    ID NUMBER(4) NOT NULL CONSTRAINT PK_BANDOC_HOADT PRIMARY KEY ,
    MA_BANDOC NUMBER(4) NOT NULL CONSTRAINT UN_BANDOC_HOADT UNIQUE ,
    TEN_BANDOC VARCHAR2(50),
    SO_DIEN_THOAI VARCHAR2(12),
    DIA_CHI VARCHAR2(50),
    NGAY_SINH DATE,
    NGAY_TAO_TAI_KHOAN DATE,
    HANG NUMBER(1)
);

CREATE TABLE DOTATHOA_MUONSACH
(
    ID NUMBER(4) NOT NULL CONSTRAINT PK_MUONSACH_HOADT PRIMARY KEY ,
    ID_BANDOC NUMBER(4) CONSTRAINT FK_MUONSACH_BANDOC_HOADT REFERENCES SCOTT.DOTATHOA_BANDOC(ID),
    ID_SACH NUMBER(4) CONSTRAINT FK_MUONSACH_SACH_HOADT REFERENCES SCOTT.DOTATHOA_SACH(ID),
    SO_LUONG NUMBER(3),
    NGAY_GIO_MUON DATE,
    NGAY_GIO_TRA DATE,
    TRANG_THAI NUMBER(1),
    GHI_CHU VARCHAR2(100)
)PARTITION BY RANGE (NGAY_GIO_MUON)
(
    PARTITION THANG1 VALUES LESS THAN (TO_DATE('01-01-2022','DD-MM,YYYY')),
    PARTITION THANG2 VALUES LESS THAN (TO_DATE('01-02-2022','DD-MM,YYYY')),
    PARTITION THANG3 VALUES LESS THAN (TO_DATE('01-03-2022','DD-MM,YYYY')),
    PARTITION THANG4 VALUES LESS THAN (TO_DATE('01-04-2022','DD-MM,YYYY')),
    PARTITION THANG8 VALUES LESS THAN (TO_DATE('01-09-2022','DD-MM,YYYY'))
);

-- 1.	Viết script tạo cấu trúc các bảng. Đối với bảng Mượn Sách cần đánh
-- partition trên trường ngày giờ mượn, và 2 local index: 1 index trên trường
-- id bạn đọc, 1 index trên id sách. Tên indexes theo cấu trúc :
-- TENBANG_IDX_TENTRUONG
CREATE INDEX DOTATHOA_BANDOC_IDX_ID ON DOTATHOA_BANDOC(ID);
CREATE INDEX DOTATHOA_SACH_IDX_ID ON DOTATHOA_SACH(ID);


-- 2.	Viết script tạo sequence cho mỗi bảng. Sequence được dùng để insert
-- trường Id cho các bảng. Tên sequence theo cấu trúc : TENBANG_SEQ
CREATE SEQUENCE NHAXUATBAN_SEQ_HOADT INCREMENT BY 1 START WITH 1 NOCYCLE;
CREATE SEQUENCE TACGIA_SEQ_HOADT INCREMENT BY 1 START WITH 1 NOCYCLE;
CREATE SEQUENCE SACH_SEQ_HOADT INCREMENT BY 1 START WITH 1 NOCYCLE;
CREATE SEQUENCE BANDOC_SEQ_HOADT INCREMENT BY 1 START WITH 1 NOCYCLE;
CREATE SEQUENCE MUONSACH_SEQ_HOADT INCREMENT BY 1 START WITH 1 NOCYCLE;

-- 3.	Viết script tạo unique index cho các bảng nếu có.


-- 4.	Viết script insert dữ liệu mẫu cho tất cả các bảng.
INSERT INTO DOTATHOA_NHAXUATBAN(ID, MA_NXB, TEN_NXB, TRANG_THAI, DIA_CHI, MO_TA)
VALUES (NHAXUATBAN_SEQ_HOADT.nextval,1001,'KIM ĐỒNG',1,'VĨNH PHÚC','A');
INSERT INTO DOTATHOA_NHAXUATBAN(ID, MA_NXB, TEN_NXB, TRANG_THAI, DIA_CHI, MO_TA)
VALUES (NHAXUATBAN_SEQ_HOADT.nextval,1002,'TRẺ',1,'HÀ NỘI','B');
INSERT INTO DOTATHOA_NHAXUATBAN(ID, MA_NXB, TEN_NXB, TRANG_THAI, DIA_CHI, MO_TA)
VALUES (NHAXUATBAN_SEQ_HOADT.nextval,1003,'HỒ CHÍ MINH',1,'THANH HÓA','C');
INSERT INTO DOTATHOA_NHAXUATBAN(ID, MA_NXB, TEN_NXB, TRANG_THAI, DIA_CHI, MO_TA)
VALUES (NHAXUATBAN_SEQ_HOADT.nextval,1004,'CHÍNH TRỊ QUỐC GIA',1,'TRÀ VINH','D');
INSERT INTO DOTATHOA_NHAXUATBAN(ID, MA_NXB, TEN_NXB, TRANG_THAI, DIA_CHI, MO_TA)
VALUES (NHAXUATBAN_SEQ_HOADT.nextval,1005,'GIÁO DỤC',1,'ĐỒNG NAI','E');
SELECT * FROM DOTATHOA_NHAXUATBAN;

INSERT INTO DOTATHOA_TACGIA(ID, MA_TACGIA, TEN_TACGIA, SODIENTHOAI, DIA_CHI, MO_TA)
VALUES (TACGIA_SEQ_HOADT.nextval,2001,'NGUYỄN NHẬT ÁNH','0987635678','ĐỒNG THÁP','GG');
INSERT INTO DOTATHOA_TACGIA(ID, MA_TACGIA, TEN_TACGIA, SODIENTHOAI, DIA_CHI, MO_TA)
VALUES (TACGIA_SEQ_HOADT.nextval,2002,'TRANG HẠ','0876524567','AN GIANG','FF');
INSERT INTO DOTATHOA_TACGIA(ID, MA_TACGIA, TEN_TACGIA, SODIENTHOAI, DIA_CHI, MO_TA)
VALUES (TACGIA_SEQ_HOADT.nextval,2003,'NGUYỄN PHONG VIỆT','0983761543','BẠC LIÊU','WW');
INSERT INTO DOTATHOA_TACGIA(ID, MA_TACGIA, TEN_TACGIA, SODIENTHOAI, DIA_CHI, MO_TA)
VALUES (TACGIA_SEQ_HOADT.nextval,2004,'ANH KHANG','0236478976','NAM ĐỊNH','GG');
INSERT INTO DOTATHOA_TACGIA(ID, MA_TACGIA, TEN_TACGIA, SODIENTHOAI, DIA_CHI, MO_TA)
VALUES (TACGIA_SEQ_HOADT.nextval,2005,'NGUYỄN NGỌC THẠCH','0612546786','HẢI DƯƠNG','NN');
SELECT * FROM DOTATHOA_TACGIA;

INSERT INTO DOTATHOA_SACH(ID, MA_SACH, TEN_SACH, ID_NXB, ID_TACGIA, CHU_DE, NAM_XUAT_BAN, MO_TA, SO_LUONG_CON_LAI, SO_LUONG_DANG_MUON, TONG_SO_SACH)
VALUES (SACH_SEQ_HOADT.nextval,'3001','ĐẮC NHÂN TÂM',2,2,'TÂM HỒN','03-DEC-2009','SS',500,10,510);
INSERT INTO DOTATHOA_SACH(ID, MA_SACH, TEN_SACH, ID_NXB, ID_TACGIA, CHU_DE, NAM_XUAT_BAN, MO_TA, SO_LUONG_CON_LAI, SO_LUONG_DANG_MUON, TONG_SO_SACH)
VALUES (SACH_SEQ_HOADT.nextval,'3002','CÁCH NGHĨ ĐỂ THÀNH CÔNG',3,3,'SUY NGHĨ','04-DEC-2010','SS',500,10,510);
INSERT INTO DOTATHOA_SACH(ID, MA_SACH, TEN_SACH, ID_NXB, ID_TACGIA, CHU_DE, NAM_XUAT_BAN, MO_TA, SO_LUONG_CON_LAI, SO_LUONG_DANG_MUON, TONG_SO_SACH)
VALUES (SACH_SEQ_HOADT.nextval,'3003','7 THÓI QUEN CỦA NGƯỜI THÀNH ĐẠT',4,4,'Ý CHÍ','05-NOV-2019','SS',500,10,510);
INSERT INTO DOTATHOA_SACH(ID, MA_SACH, TEN_SACH, ID_NXB, ID_TACGIA, CHU_DE, NAM_XUAT_BAN, MO_TA, SO_LUONG_CON_LAI, SO_LUONG_DANG_MUON, TONG_SO_SACH)
VALUES (SACH_SEQ_HOADT.nextval,'3004','CUỘC SỐNG KHÔNG GIỚI HẠN',5,5,'CUỘC SỐNG','03-AUG-2008','SS',500,10,510);
INSERT INTO DOTATHOA_SACH(ID, MA_SACH, TEN_SACH, ID_NXB, ID_TACGIA, CHU_DE, NAM_XUAT_BAN, MO_TA, SO_LUONG_CON_LAI, SO_LUONG_DANG_MUON, TONG_SO_SACH)
VALUES (SACH_SEQ_HOADT.nextval,'3005','XYZ',2,3,'ABC','03-DEC-2013','SS',500,4,504);
SELECT * FROM DOTATHOA_SACH;

INSERT INTO DOTATHOA_BANDOC(ID, MA_BANDOC, TEN_BANDOC, SO_DIEN_THOAI, DIA_CHI, NGAY_SINH, NGAY_TAO_TAI_KHOAN, HANG)
VALUES (BANDOC_SEQ_HOADT.nextval,4001,'ĐỖ TẤT HÒA','0987656387','THANH HÓA','21-SEP-2002','01-JAN-2022',1);
INSERT INTO DOTATHOA_BANDOC(ID, MA_BANDOC, TEN_BANDOC, SO_DIEN_THOAI, DIA_CHI, NGAY_SINH, NGAY_TAO_TAI_KHOAN, HANG)
VALUES (BANDOC_SEQ_HOADT.nextval,4002,'THIỀU QUANG VINH','0917656387','HÀ NAM','21-AUG-2002','02-JAN-2022',2);
INSERT INTO DOTATHOA_BANDOC(ID, MA_BANDOC, TEN_BANDOC, SO_DIEN_THOAI, DIA_CHI, NGAY_SINH, NGAY_TAO_TAI_KHOAN, HANG)
VALUES (BANDOC_SEQ_HOADT.nextval,4003,'TRẦN ĐỨC PHƯƠNG','0982656387','VĨNH PHÚC','21-JUL-2002','03-JAN-2022',2);
INSERT INTO DOTATHOA_BANDOC(ID, MA_BANDOC, TEN_BANDOC, SO_DIEN_THOAI, DIA_CHI, NGAY_SINH, NGAY_TAO_TAI_KHOAN, HANG)
VALUES (BANDOC_SEQ_HOADT.nextval,4004,'LÊ MINH THỤY','0987653387','HÀ NỘI','21-JUN-2002','04-JAN-2022',3);
INSERT INTO DOTATHOA_BANDOC(ID, MA_BANDOC, TEN_BANDOC, SO_DIEN_THOAI, DIA_CHI, NGAY_SINH, NGAY_TAO_TAI_KHOAN, HANG)
VALUES (BANDOC_SEQ_HOADT.nextval,4005,'NGUYỄN VIẾT HIÊN','0947656387','BẮC NINH','21-MAY-2002','05-JAN-2022',3);
SELECT * FROM DOTATHOA_BANDOC;

INSERT INTO DOTATHOA_MUONSACH(ID, ID_BANDOC, ID_SACH, SO_LUONG, NGAY_GIO_MUON, NGAY_GIO_TRA, TRANG_THAI, GHI_CHU)
VALUES (MUONSACH_SEQ_HOADT.nextval,6,10,10,'12-JAN-2022','14-JAN-2022',1,'NO');
INSERT INTO DOTATHOA_MUONSACH(ID, ID_BANDOC, ID_SACH, SO_LUONG, NGAY_GIO_MUON, NGAY_GIO_TRA, TRANG_THAI, GHI_CHU)
VALUES (MUONSACH_SEQ_HOADT.nextval,7,11,10,'13-FEB-2022','15-FEB-2022',2,'NO');
INSERT INTO DOTATHOA_MUONSACH(ID, ID_BANDOC, ID_SACH, SO_LUONG, NGAY_GIO_MUON, NGAY_GIO_TRA, TRANG_THAI, GHI_CHU)
VALUES (MUONSACH_SEQ_HOADT.nextval,8,12,10,'10-MAR-2022','12-MAR-2022',2,'NO');
INSERT INTO DOTATHOA_MUONSACH(ID, ID_BANDOC, ID_SACH, SO_LUONG, NGAY_GIO_MUON, NGAY_GIO_TRA, TRANG_THAI, GHI_CHU)
VALUES (MUONSACH_SEQ_HOADT.nextval,9,13,10,'09-MAR-2022','11-APR-2022',1,'NO');
INSERT INTO DOTATHOA_MUONSACH(ID, ID_BANDOC, ID_SACH, SO_LUONG, NGAY_GIO_MUON, NGAY_GIO_TRA, TRANG_THAI, GHI_CHU)
VALUES (MUONSACH_SEQ_HOADT.nextval,9,13,10,'09-AUG-2022','11-AUG-2022',1,'NO');
SELECT * FROM DOTATHOA_MUONSACH;

-- 5.	Hiển thị dách sách tác giả và tổng số lượng sách của tác giả gồm
-- các trường thông tin:
-- Mã Tác Giả, Tên Tác Giả, Chủ Đề, Số Lượng Sách
-- Sắp xếp theo số lượng sách giảm dần
SELECT MA_TACGIA,TEN_TACGIA,CHU_DE,SO_LUONG_CON_LAI
FROM DOTATHOA_SACH S , DOTATHOA_TACGIA T
WHERE S.ID_TACGIA = T.ID
ORDER BY SO_LUONG_CON_LAI DESC ;

-- 6.	Hiển thị 10 quyển sách có số lượng được mượn nhiều nhất gồm các trường thông tin:
-- Mã Sách, Tên Sách, Tên Nhà Xuất Bản, Tên Tác Giả, Chủ Đề, Năm Xuất Bản, Số Lượng Còn Lại,
-- Số Lượng Đã Mượn, Tổng Số
SELECT *
FROM (
         SELECT MA_SACH,
                TEN_SACH,
                TEN_NXB,
                TEN_TACGIA,
                CHU_DE,
                TO_CHAR(NAM_XUAT_BAN,'DD-MM-YYYY') AS NAM_XB,
                SO_LUONG_CON_LAI,
                SO_LUONG_DANG_MUON,
                TONG_SO_SACH
         FROM DOTATHOA_SACH S,DOTATHOA_NHAXUATBAN N, DOTATHOA_TACGIA T
         WHERE S.ID_TACGIA = T.ID AND
                 S.ID_NXB = N.ID
     )
WHERE ROWNUM < 11

-- 7.	Hiển thị  thông tin bạn đọc và sách được mượn từ ngày đầu
-- tháng hiện tại đến thời điểm hiện tại.
-- Mã Bạn Đọc, Tên Bạn Đọc, Mã Sách, Tên Sách, Ngày Giờ Mượn, Số lượng
-- Sắp xếp theo ngày giờ mượn giảm dần, Tên bạn đọc tăng dần.
SELECT MA_BANDOC, TEN_BANDOC, MA_SACH, TEN_SACH, NGAY_GIO_MUON, SO_LUONG
FROM DOTATHOA_BANDOC B, DOTATHOA_SACH S, DOTATHOA_MUONSACH M
WHERE M.ID_BANDOC = B.ID AND
        M.ID_SACH = S.ID AND
    (NGAY_GIO_MUON BETWEEN TRUNC(SYSDATE,'MONTH') AND SYSDATE)
ORDER BY NGAY_GIO_MUON DESC, TEN_BANDOC ASC;

-- 8.	Hiển thị 10 quyển sách có số lượng được mượn nhiều nhất
-- tính từ đầu năm 2022
-- Mã Sách, Tên Sách, Số Lượng Đã Được Mượn.
SELECT *
FROM (
         SELECT MA_SACH,TEN_SACH,SUM(SO_LUONG_DANG_MUON) AS SL
         FROM DOTATHOA_SACH S, DOTATHOA_MUONSACH M
         WHERE S.ID = M.ID_SACH AND
                 TO_CHAR(NGAY_GIO_MUON,'YYYY') >= 2022
         GROUP BY MA_SACH, TEN_SACH
         ORDER BY SL DESC
     )
WHERE ROWNUM < 11;


-- 9.	Hiển thị danh sách bạn đọc và số lần mượn sách tính
-- từ đầu năm 2022 sắp xếp theo tên bạn đọc tăng dần:
-- Mã Bạn Đọc, Tên Bạn Đọc, Số Lần Mượn
SELECT MA_BANDOC, TEN_BANDOC, COUNT(B.ID) AS SL_MUON
FROM DOTATHOA_BANDOC B, DOTATHOA_MUONSACH M
WHERE B.ID = M.ID_BANDOC AND
        TO_CHAR(NGAY_GIO_MUON,'YYYY') >= 2022
GROUP BY MA_BANDOC, TEN_BANDOC
ORDER BY TEN_BANDOC ASC

-- 10.	Hiển thị thông tin bạn đọc gồm có:
-- Mã Bạn Đọc, Tên Bạn Đọc, Tuổi (được tính dựa vào trường ngày sinh)
SELECT MA_BANDOC,TEN_BANDOC, TO_CHAR(SYSDATE,'YYYY') - TO_CHAR(NGAY_SINH,'YYYY') AS TUOI
FROM DOTATHOA_BANDOC B;

-- 11.	Thống kê tổng số bạn đọc theo độ tuổi
-- Tuổi, Tổng số Bạn Đọc
SELECT TO_CHAR(SYSDATE,'YYYY') - TO_CHAR(NGAY_SINH,'YYYY') AS TUOI,
       COUNT(TO_CHAR(SYSDATE,'YYYY') - TO_CHAR(NGAY_SINH,'YYYY')) AS TONG_SO_BAN_DOC
FROM DOTATHOA_BANDOC
GROUP BY (TO_CHAR(SYSDATE,'YYYY') - TO_CHAR(NGAY_SINH,'YYYY'));

--12.	Thống kê số lượng sách được xuất bản theo Nhà Xuất Bản, Theo năm xuất bản.
-- Năm Xuất Bản, Mã Nhà Xuất Bản,Tên Nhà Xuất Bản, Số Lượng Sách
-- Sắp xếp theo Năm xuất bản giảm dần, Tên Nhà xuất bản tăng dần.
SELECT TO_CHAR(NAM_XUAT_BAN,'YYYY') AS NAM_XUAT_BAN_T, MA_NXB, TEN_NXB, SUM(TONG_SO_SACH) AS SO_LUONG_SACH
FROM DOTATHOA_NHAXUATBAN N, DOTATHOA_SACH S
WHERE N.ID = S.ID_NXB
GROUP BY TO_CHAR(NAM_XUAT_BAN,'YYYY'), MA_NXB, TEN_NXB
ORDER BY NAM_XUAT_BAN_T DESC , TEN_NXB ASC;

-- 13.	Hiển thị 5 quyển sách được các bạn đọc có độ tuổi từ 18 đến 25
-- mượn nhiều nhất tính từ đầu năm 2022. (Tính theo trường số lượng mượn
-- của sách)
-- Mã Sách, Tên Sách, Số Lượng Được Mượn
SELECT *
FROM (
         SELECT MA_SACH, TEN_SACH, SO_LUONG_DANG_MUON
         FROM DOTATHOA_SACH S JOIN DOTATHOA_MUONSACH M ON S.ID = M.ID_SACH
                              JOIN DOTATHOA_BANDOC B ON M.ID_BANDOC = B.ID
         WHERE (TO_CHAR(SYSDATE,'YYYY') - TO_CHAR(NGAY_SINH,'YYYY')) BETWEEN 18 AND 25
     )
WHERE ROWNUM < 6;

--14.	Hiển thị toàn bộ bạn đọc và sách mà bạn đọc đấy mượn,
-- sẽ có bạn chưa mượn vẫn cần hiển thị và tên sách để là null.
-- Mã bạn đọc, tên ban đọc, tên sách