--BÀI TẬP CHƯƠNG 10
--1. Tạo view có hiển thị như sau:
CREATE VIEW AGGREDATES_HOADT
AS
SELECT *
FROM AGGREDATES

SELECT *
FROM AGGREDATES_HOADT

--2. Tạo view để nhập số liệu vào bảng ASIGNMENT với các điều kiện sau
CREATE VIEW ASSIGNMENT_VIEW_HOADT
AS
SELECT *
FROM ASSIGNMENTS_HOADT
WHERE PROJID < 2000
  AND A_START_DATE < A_END_DATE
  AND EMPNO IS NOT NULL
  AND ((BILL_AMOUNT < 50 AND ASSIGN_TYPE = 'PS') OR
       (BILL_AMOUNT < 60 AND ASSIGN_TYPE = 'WT') OR
       (BILL_AMOUNT < 70 AND ASSIGN_TYPE = 'ED'))
WITH CHECK OPTION CONSTRAINT ASSIGNMENTS_VIEW_HOADT_CHECK;

INSERT INTO ASSIGNMENT_VIEW_HOADT(PROJID, EMPNO, A_START_DATE, A_END_DATE, BILL_AMOUNT, ASSIGN_TYPE, HOURS)
VALUES (4, 8009, '23-JAN-2020', '24-JAN-2020', 59, 'WT', 20);

--3. Định nghĩa bảng MESSAGES có cấu trúc
CREATE TABLE MESSAGES_HOADT
(
    NUMCOL1  NUMBER(9, 2),
    NUMCOL2  NUMBER(9, 2),
    CHARCOL1 VARCHAR2(60),
    CHARCOL2 VARCHAR2(60),
    DATECOL1 DATE,
    DATECOL2 DATE
);

CREATE VIEW MESSAGE_VIEW_HOADT
AS
    SELECT * FROM MESSAGES_HOADT;